name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 'publish'
        run: |
          npm ci
          npm run build
          npm ci --omit=dev
          npm config set "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" --userconfig .npmrc
          npm publish
